config/routes.rb
Rails.application.routes.draw do
  resources :categories, except: [:edit, :update]
  resources :recipes
  root "categories#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :recipes, dependent: :delete_all
  ICONS = ["bread", "cookies", "cupcake", "flour", "pancakes", "pie", "rice", "steak"].map { |s| "#{s}.png" }
  validates_inclusion_of :icon, :in => ICONS
  validates :name, :icon, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :category
  accepts_nested_attributes_for :category
  validates :name, :ingredients, :instructions, :category, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :warning, :danger, :info
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all.order("name ASC")
  end

  def new
    @category = Category.new
    @images = Dir.glob("#{Rails.root}/app/assets/images/food/*.png")
  end

  def create
    @category = Category.new(category_params)
    @images = Dir.glob("#{Rails.root}/app/assets/images/food/*.png")

    if @category.save
      redirect_to root_path, :success => "Created new category: #{@category.name}"
    else
      render :new
    end
  end

  def show
    @category = Category.find(params[:id])
    @recipes = @category.recipes
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to root_path, :success => "Removed category: #{@category.name}"
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def show
    @recipe = Recipe.find(params[:id])
    @category = Category.find(@recipe.category_id)
  end

  def new
    @recipe = Recipe.new
    @recipe.build_category
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @category = @recipe.category
    if @recipe.save
      redirect_to category_path(@category), :success => "#{@recipe.name} recipe created!"
    else
      render "new"
    end
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update_attributes(recipe_params)
      redirect_to @recipe, :success => "#{@recipe.name} recipe updated"
    else
      render "edit"
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
    @category = Category.find(@recipe.category_id)
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @category = Category.find(@recipe.category_id)
    @recipe.destroy
    redirect_to @category, :success => "Removed recipe: #{@recipe.name}"
  end

  private

  def recipe_params
    params.require(:recipe).permit(:category_id, :name, :time_estimate, :ingredients, :instructions)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def img_file_name(img)
    img.split("/").last
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def minutes_with_clock(minutes)
    minutes = minutes.to_s
    "#{fa_icon "clock-o"}#{minutes}m".html_safe
  end
end

app/views/categories/_categorybox.html.erb
<%= link_to cat do %>
<div class="box">
    <p class="subtitle has-text-centered">
        <%= image_tag "food/#{cat.icon}" %>
    </p>
    <p class="has-text-centered has-text-weight-bold">
        <%= cat.name %>
    </p>
</div>
<% end %>

app/views/categories/_form.html.erb
<%= simple_form_for @category do |f| %>
<div class="field">
    <%= f.input :name, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
</div>
<!-- icon selection -->
<div class="field">
    <label class="label">Icon (select one)</label>
    <div class="level">
        <% @images.each do |iconImage| %>
        <%= render partial: "iconRadioBox", locals: {f: f, image: iconImage} %>
        <% end %>
    </div>
</div>

<br />

<%= f.button :submit, class: "button is-primary" %>
<% end %>

app/views/categories/_iconRadioBox.html.erb
<div class="level-item">
    <%= f.radio_button :icon, img_file_name(image), class: "icon-radio" %>
    <%= f.label :icon, value: img_file_name(image) do %>
    <div class="box">
        <div class="circle"></div>
        <%= image_tag "food/#{img_file_name(image)}" %>
    </div>
    <% end %>
</div>

app/views/categories/_recipebox.html.erb
<div class="card">
    <%= link_to recipe_path(recipe) do %>
    <header class="card-header">
        <p class="card-header-title">
            <%= recipe.name %>
        </p>
        <p class="card-header-icon">
            <%= fa_icon "angle-right" %>
        </p>
    </header>
    <% end %>
    <div class="card-content">
        <div class="content">
            <a href="#">#fancy</a> <a href="#">#quick</a>
            <%= truncate(raw(recipe.ingredients), length: 50) %>
        </div>
    </div>
    <footer class="card-footer">
        <p class="card-footer-item"> <%= fa_icon "clock-o" %><%= recipe.time_estimate %>m </p>
        <%= link_to 'Edit', edit_recipe_path(recipe), class: 'card-footer-item' %>
        <%= link_to recipe, method: :delete, data: {confirm: "Delete recipe: #{recipe.name}?"}, class: 'card-footer-item has-text-danger' do %>
        <%= fa_icon 'trash' %>
        <% end %>
    </footer>
</div>

app/views/categories/index.html.erb
<h1 class="title is-1 has-text-centered">Pantry Book</h1>

<div id="search-bar" class="field has-addons">
    <div class="control is-expanded">
        <input class="input" type="text" placeholder="Find a recipe">
    </div>
    <div class="control">
        <a class="button">
            Search
        </a>
    </div>
</div>

<hr />

<div class="level">
    <%= link_to "+ New Category", new_category_path, class: "button is-primary is-light" %>
</div>
<div class="columns is-multiline">
    <% @categories.each do |cat| %>
    <div class="column is-one-quarter">
        <%= render partial: "categorybox", locals: {cat: cat} %>
    </div>
    <% end %>
</div>

app/views/categories/new.html.erb
<h1 class="title">New Category</h1>

<%= render "form" %>

app/views/categories/show.html.erb
<h1 class="title is-1 has-text-centered">
    <%= @category.name %>
    <%= image_tag "food/#{@category.icon}" %>
</h1>

<hr />

<section>
    <div id="recipe-cards">
        <% @recipes.each do |r| %>
        <%= render partial: "recipes/recipebox", locals: {recipe: r} %>
        <% end %>
    </div>
</section>

<%= link_to @category, method: :delete, data: {confirm: "Delete category for good?"}, class: "button is-danger" do %>
Remove Category
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Pantry Book</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <%= link_to 'PantryBook', root_path, class: 'navbar-item' %>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-end">
        <div class="navbar-item">
          <div class="buttons">
            <%= link_to 'New Recipe', new_recipe_path, class: "button is-primary" %>
          </div>
        </div>
      </div>
    </div>
  </nav>
  <% flash.each do |name, msg| %>
  <div class="notification is-<%= name %>"><button class="delete"></button><%= msg %></div>
  <% end %>
  <div class="container section">
    <%= yield %>
  </div>
  <footer class="footer">
    <div class="content has-text-centered">
      <p>
        <strong>PantryBook</strong> by <a href="https://mroudnitski.com">Michael Roudnitski</a>
      </p>
    </div>
  </footer>
</body>


<script>
  document.addEventListener('DOMContentLoaded', () => {
    (document.querySelectorAll('.notification .delete') || []).forEach(($delete) => {
      $notification = $delete.parentNode;

      $delete.addEventListener('click', () => {
        $notification.parentNode.removeChild($notification);
      });
    });
  });
</script>

</html>

app/views/recipes/_form.html.erb
<%= simple_form_for @recipe do |f|%>

<div class="field">
    <div class="label">
        Category
    </div>
    <div class="select">
        <div class="control">
            <%= f.association :category, wrapper: false, label:false, date_separator: '</div><div class="select">', include_blank: false %>
        </div>
    </div>
</div>

<div class="field">
    <%= f.input :name, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label' } %>
</div>

<div class="field">
    <%= f.input :time_estimate, as: :integer, wrapper: false, input_html: { class: 'input' }, label_html: { class: 'label' }, label: "Estimated Time (minutes)" %>
</div>

<div class="field">
    <%= f.input :ingredients, as: :ckeditor, wrapper: false, input_html: {ckeditor: {toolbar: 'mini' }}, label_html: { class: 'label' } %>
</div>

<div class="field">
    <%= f.input :instructions, as: :ckeditor, wrapper: false, input_html: {ckeditor: {toolbar: 'mini' }}, label_html: { class: 'label' } %>
</div>


<div class="field is-grouped-right">
    <%= f.button :submit, class: "button is-primary" %>
</div>

<% end %>

<%= javascript_include_tag Ckeditor.cdn_url %>

app/views/recipes/_recipebox.html.erb
<div class="card">
    <%= link_to recipe_path(recipe) do %>
    <header class="card-header">
        <p class="card-header-title">
            <%= recipe.name %>
        </p>
        <p class="card-header-icon">
            <%= fa_icon "angle-right" %>
        </p>
    </header>
    <% end %>
    <div class="card-content">
        <div class="content">
            <a href="#">#fancy</a> <a href="#">#quick</a>
            <%= raw(recipe.ingredients) %>
        </div>
    </div>
    <footer class="card-footer">
        <%# minutes_with_clock, class="card-footer-item" %>
        <p class="card-footer-item"> <%= minutes_with_clock(recipe.time_estimate) %></p>
        <%= link_to 'Edit', edit_recipe_path(recipe), class: 'card-footer-item' %>
        <%= link_to recipe, method: :delete, data: {confirm: "Delete recipe: #{recipe.name}?"}, class: 'card-footer-item has-text-danger' do %>
        <%= fa_icon 'trash' %>
        <% end %>
    </footer>
</div>

app/views/recipes/edit.html.erb
<h1 class="title is-1 has-text-centered">Edit <%= @recipe.name %></h1>

<%= render "form" %>

app/views/recipes/new.html.erb
<h1 class="title is-1 has-text-centered">New Recipe</h1>

<%= render "form" %>

app/views/recipes/show.html.erb
<div class="level">
    <div class="level-left">
        <div class="level-item">
            <%= link_to @category do %>
            <h1 class="title is-3 has-text-weight-light"><u><%= @category.name %></u></h1>
            <% end %>
            <h1 class="title is-3 has-text-weight-bold">/<%= @recipe.name %></h1>
        </div>
    </div>
    <div class="level-right">
        <div class="level-item">
            <%= minutes_with_clock(@recipe.time_estimate) %>
        </div>
        <div class="dropdown is-hoverable level-item is-right">
            <div class="dropdown-trigger">
                <button class="button" aria-haspopup="true" aria-controls="dropdown-menu4">
                    <span> <%= fa_icon 'cog' %> </span>
                </button>
            </div>
            <div class="dropdown-menu" role="menu">
                <div class="dropdown-content">
                    <div class="dropdown-item">
                        <%= link_to 'Edit', edit_recipe_path(@recipe), class: 'card-footer-item' %>
                    </div>
                    <div class="dropdown-item">
                        <%= link_to "Delete Recipe", @recipe, method: :delete, data: {confirm: "Delete recipe: #{@recipe.name}?"}, class: 'card-footer-item has-text-danger' %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<hr />

<div class="columns">
    <div class="column content">
        <h3>Ingredients</h3>
        <div class="content box scrollable-content">
            <%= raw(@recipe.ingredients) %>
        </div>
    </div>
    <div class="column content">
        <h3>Instructions</h3>
        <div class="content box scrollable-content">
            <%= raw(@recipe.instructions) %>
        </div>
    </div>
</div>